version: '3'

services:
  mysql:
    build: build/mysql
    image: testtask/mysql
    restart: always
    container_name: testtask-mysql
    volumes:
      - "./volumes/mydata:/var/lib/mysql"
      - "./volumes/data:/opt/data"
      - "./build/mysql/conf.d:/etc/mysql/conf.d"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: testtask
      MYSQL_ROOT_PASSWORD: testtask
      MYSQL_PASSWORD: testtask
      MYSQL_USER: testtask
